# Generated by Django 5.2.14 on 2026-06-02 12:28

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_string', models.TextField(help_text='host:port:username:password or host:port')),
                ('proxy_type', models.CharField(choices=[('socks5', 'SOCKS5'), ('http', 'HTTP')], default='socks5', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_working', models.BooleanField(default=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'ordering': ['fail_count', 'id'],
                'unique_together': {('proxy_string', 'proxy_type')},
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('api_id', models.CharField(default=accounts.models.get_default_api_id, max_length=20)),
                ('api_hash', models.CharField(default=accounts.models.get_default_api_hash, max_length=64)),
                ('session_string', models.TextField(blank=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('auth_code_hash', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram акаунт',
                'verbose_name_plural': 'Telegram акаунти',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
