# Generated by Django 5.2.14 on 2026-06-02 12:37

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['fail_count', 'id'], 'verbose_name': 'Проксі', 'verbose_name_plural': 'Проксі'},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='fail_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість відмов'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Працює'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання перевірка'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_string',
            field=models.TextField(help_text='Формат: host:port:username:password або host:port', verbose_name='Проксі-рядок'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(choices=[('socks5', 'SOCKS5'), ('http', 'HTTP')], default='socks5', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(default=accounts.models.get_default_api_hash, help_text='Telegram API Hash з my.telegram.org (за замовчуванням з TELEGRAM_API_HASH)', max_length=64, verbose_name='API Hash'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_id',
            field=models.CharField(default=accounts.models.get_default_api_id, help_text='Telegram API ID з my.telegram.org (за замовчуванням з TELEGRAM_API_ID)', max_length=20, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='auth_code_hash',
            field=models.CharField(blank=True, help_text='Тимчасовий хеш для верифікації коду', max_length=100, verbose_name='Хеш коду'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Авторизовано'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останнє використання'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='name',
            field=models.CharField(help_text='Зручна назва для цього акаунту', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(help_text='Номер телефону з кодом країни (напр., +380501234567)', max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxy', verbose_name='Проксі'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='session_string',
            field=models.TextField(blank=True, help_text='Telethon session string (генерується автоматично після авторизації)', verbose_name='Сесія'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
