# Generated by Django 5.2.16 on 2026-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_proxy_options_alter_proxy_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='app_version',
            field=models.CharField(blank=True, help_text='Напр. «3.4.3 x64».', max_length=64, verbose_name='Версія застосунку'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='device_model',
            field=models.CharField(blank=True, help_text='Напр. «Lenovo G50-80». Порожньо — дефолт Telethon.', max_length=100, verbose_name='Модель пристрою'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='lang_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Мова клієнта'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='system_lang_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Мова системи'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='system_version',
            field=models.CharField(blank=True, help_text='Напр. «Windows 10».', max_length=64, verbose_name='Версія ОС'),
        ),
    ]
