# Generated by Django 5.2.16 on 2026-09-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_app_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=32, verbose_name='Запуск')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок у запуску')),
                ('bot_username', models.CharField(max_length=64, verbose_name='Бот')),
                ('feedback_text', models.CharField(max_length=200, verbose_name='Текст відгуку')),
                ('pause_min', models.PositiveIntegerField(verbose_name='Пауза від, хв')),
                ('pause_max', models.PositiveIntegerField(verbose_name='Пауза до, хв')),
                ('status', models.CharField(choices=[('queued', 'У черзі (чекає попереднього)'), ('pending', 'Готове до запуску'), ('running', 'Виконується'), ('done', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], db_index=True, default='queued', max_length=10, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Гейт готовності: pending-завдання забирається воркером лише після цього часу.', null=True, verbose_name='Не раніше')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Захоплено')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Спроб')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат (кроки)')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bot_jobs', to='accounts.telegramaccount', verbose_name='Акаунт')),
            ],
            options={
                'verbose_name': 'Тестовий прогін бота — завдання',
                'verbose_name_plural': 'Тестовий прогін бота — завдання',
                'ordering': ['batch_id', 'order'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='accounts_te_status_d2b206_idx'), models.Index(fields=['batch_id', 'order'], name='accounts_te_batch_i_fa5c59_idx')],
            },
        ),
    ]
