# Generated by Django 5.2.16 on 2026-09-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_testbotjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmUpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handles', models.JSONField(verbose_name='Канали (username без @)')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('done', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Захоплено')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Спроб')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат (joined/failed)')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warm_up_jobs', to='accounts.telegramaccount', verbose_name='Акаунт')),
            ],
            options={
                'verbose_name': 'Прогрів акаунта — завдання',
                'verbose_name_plural': 'Прогрів акаунта — завдання',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_wa_status_98e75e_idx')],
            },
        ),
    ]
