# Generated by Django 5.2.16 on 2026-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_warmupjob'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warmupjob',
            name='accounts_wa_status_98e75e_idx',
        ),
        migrations.AddField(
            model_name='warmupjob',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Гейт готовності для ретраю — pending-завдання забирається лише після цього часу.', null=True, verbose_name='Не раніше'),
        ),
        migrations.AddIndex(
            model_name='warmupjob',
            index=models.Index(fields=['status', 'scheduled_at'], name='accounts_wa_status_4ea5a0_idx'),
        ),
    ]
