# Generated by Django 5.2.16 on 2026-09-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_warmupjob_accounts_wa_status_98e75e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='spam_status',
            field=models.CharField(choices=[('unknown', 'Невідомо'), ('free', 'Без обмежень'), ('limited', 'Обмежений'), ('frozen', 'Заморожений')], default='unknown', max_length=10, verbose_name='Статус (SpamBot)'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='spam_status_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перевірено (SpamBot)'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='spam_status_detail',
            field=models.CharField(blank=True, max_length=300, verbose_name='Відповідь SpamBot'),
        ),
    ]
