# Generated by Django 5.2.16 on 2026-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telegramaccount_spam_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Тег акаунта',
                'verbose_name_plural': 'Теги акаунтів',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='accounts.accounttag', verbose_name='Теги'),
        ),
    ]
