# Generated by Django 5.2.16 on 2026-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounttag_telegramaccount_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='two_fa_password',
            field=models.CharField(blank=True, help_text='Хмарний пароль (2FA), якщо відомий — знадобиться для повторної авторизації, якщо сесія злетить. Зберігається як є (без хешування), як і session_string.', max_length=200, verbose_name='Пароль 2FA'),
        ),
    ]
