# Generated by Django 5.2.16 on 2026-09-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_telegramaccount_two_fa_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.telegramaccount', verbose_name='Акаунт-власник')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боти',
                'ordering': ['username'],
            },
        ),
    ]
