# Generated by Django 5.2.17 on 2026-09-16 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_telegrambot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Порожньо — спільний акаунт (бачать усі). Власник бачить лише свої акаунти й спільні; суперюзер — усі.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_telegram_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
    ]
