# Generated by Django 5.2.14 on 2026-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_resolve_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='state',
            field=models.CharField(choices=[('ready', 'Готовий'), ('cooldown', 'Пауза (cooldown)'), ('needs_proxy', 'Потрібна проксі'), ('deauthorized', 'Розлогінений'), ('banned', 'Забанений'), ('frozen', 'Заморожений')], default='ready', max_length=16, verbose_name='Стан'),
        ),
    ]
