# Generated by Django 5.2.14 on 2026-06-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('telezip_query', models.TextField(help_text='TeleZip search query (text= syntax)')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('languages', models.JSONField(blank=True, default=list, help_text='e.g. ["ru"]')),
                ('channels_only', models.BooleanField(default=True, help_text='Drop chats/comments')),
                ('classify_system_prompt', models.TextField(help_text="System prompt; must instruct strict JSON output with the task's fields.")),
                ('relevance_field', models.CharField(default='is_relevant', help_text='Boolean field in LLM output that gates a post into events.', max_length=50)),
                ('dedup_window_days', models.PositiveSmallIntegerField(default=3)),
                ('dedup_pre_thresh', models.PositiveSmallIntegerField(default=82, help_text='fuzzy pre-merge %')),
                ('dedup_cand_thresh', models.PositiveSmallIntegerField(default=55, help_text='candidate-pair fuzzy %')),
                ('llm_model', models.CharField(blank=True, help_text='override default model', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConflictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('family', models.CharField(blank=True, max_length=80)),
                ('region_hint', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('subscribers', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('inferred_region', models.CharField(blank=True, max_length=128)),
                ('is_channel', models.BooleanField(blank=True, help_text='False = chat/comments', null=True)),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
                ('enriched', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('tg_id__isnull', False)), fields=('tg_id',), name='uniq_channel_tgid')],
            },
        ),
        migrations.CreateModel(
            name='ConflictTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=120, unique=True)),
                ('conflict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.conflicttype')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('is_corroborated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analysis.conflicttype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analysis.analysistask')),
                ('sides', models.ManyToManyField(blank=True, related_name='events', to='analysis.nationality')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='NationalityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=120, unique=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('channel_name', models.CharField(blank=True, max_length=128)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('telezip_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=80)),
                ('telezip_mid', models.BigIntegerField(blank=True, null=True)),
                ('is_classified', models.BooleanField(default=False)),
                ('is_relevant', models.BooleanField(blank=True, null=True)),
                ('classification', models.JSONField(blank=True, default=dict)),
                ('date_enriched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.channel')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.event')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='analysis.analysistask')),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['task', 'event_date'], name='analysis_ev_task_id_d814cc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['task', 'is_classified'], name='analysis_po_task_id_fb7786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('task', 'url')},
        ),
    ]
