# Generated by Django 5.2.14 on 2026-06-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistask',
            options={'verbose_name': 'Задача аналізу', 'verbose_name_plural': 'Задачі аналізу'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Канали'},
        ),
        migrations.AlterModelOptions(
            name='conflicttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип конфлікту', 'verbose_name_plural': 'Типи конфліктів'},
        ),
        migrations.AlterModelOptions(
            name='conflicttypealias',
            options={'verbose_name': 'Аліас типу конфлікту', 'verbose_name_plural': 'Аліаси типів конфліктів'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name'], 'verbose_name': 'Національність', 'verbose_name_plural': 'Національності'},
        ),
        migrations.AlterModelOptions(
            name='nationalityalias',
            options={'verbose_name': 'Аліас національності', 'verbose_name_plural': 'Аліаси національностей'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='channels_only',
            field=models.BooleanField(default=True, help_text='Відкидати чати/коментарі, залишати лише канали', verbose_name='Тільки канали'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='classify_system_prompt',
            field=models.TextField(help_text='Системний промпт; має вимагати строгий JSON з полями задачі.', verbose_name='Системний промпт класифікації'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='date_from',
            field=models.DateField(verbose_name='Дата від'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='date_to',
            field=models.DateField(verbose_name='Дата до'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='dedup_cand_thresh',
            field=models.PositiveSmallIntegerField(default=55, help_text='Fuzzy-поріг відбору пар на перевірку LLM', verbose_name='Поріг пар-кандидатів (%)'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='dedup_pre_thresh',
            field=models.PositiveSmallIntegerField(default=82, help_text='Fuzzy-поріг для дешевого злиття майже однакових репостів', verbose_name='Поріг попереднього злиття (%)'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='dedup_window_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Вікно дедупу (днів)'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Список кодів мов, напр. ["ru"]', verbose_name='Мови'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Перевизначає модель за замовчуванням', max_length=100, verbose_name='Модель LLM'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='relevance_field',
            field=models.CharField(default='is_relevant', help_text='Булеве поле у відповіді LLM, що пропускає пост у події.', max_length=50, verbose_name='Поле релевантності'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ідентифікатор (slug)'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='telezip_query',
            field=models.TextField(help_text='Запит у синтаксисі TeleZip (text=...)', verbose_name='Пошуковий запит TeleZip'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='enriched',
            field=models.BooleanField(default=False, verbose_name='Збагачено'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отримано'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='inferred_region',
            field=models.CharField(blank=True, help_text='Регіон, визначений із назви/опису каналу (fallback)', max_length=128, verbose_name='Регіон (визначений)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_channel',
            field=models.BooleanField(blank=True, help_text='False = чат/коментарі', null=True, verbose_name='Є каналом'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.CharField(blank=True, max_length=16, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='raw_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сирі метадані'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.IntegerField(default=0, verbose_name='Підписники'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='conflicttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='conflicttype',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Назва (канонічна)'),
        ),
        migrations.AlterField(
            model_name='conflicttypealias',
            name='conflict_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.conflicttype', verbose_name='Тип конфлікту'),
        ),
        migrations.AlterField(
            model_name='conflicttypealias',
            name='raw',
            field=models.CharField(max_length=120, unique=True, verbose_name='Варіант (аліас)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conflict_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analysis.conflicttype', verbose_name='Тип конфлікту'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, help_text='З найранішого посту (дата публікації)', null=True, verbose_name='Дата події'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_corroborated',
            field=models.BooleanField(default=False, help_text='Підтверджено ≥2 каналами', verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість постів'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=128, verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sides',
            field=models.ManyToManyField(blank=True, related_name='events', to='analysis.nationality', verbose_name='Сторони'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='event',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analysis.analysistask', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='family',
            field=models.CharField(blank=True, max_length=80, verbose_name='Група/родина'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Назва (канонічна)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='region_hint',
            field=models.CharField(blank=True, max_length=128, verbose_name='Підказка регіону'),
        ),
        migrations.AlterField(
            model_name='nationalityalias',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.nationality', verbose_name='Національність'),
        ),
        migrations.AlterField(
            model_name='nationalityalias',
            name='raw',
            field=models.CharField(max_length=120, unique=True, verbose_name='Варіант (аліас)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва каналу'),
        ),
        migrations.AlterField(
            model_name='post',
            name='classification',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат класифікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Хеш контенту'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_enriched',
            field=models.BooleanField(default=False, verbose_name='Дату збагачено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.event', verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_classified',
            field=models.BooleanField(default=False, verbose_name='Класифіковано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_relevant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Релевантний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Надійна дата (Telethon/TeleZip, UTC)', null=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='analysis.analysistask', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='post',
            name='telezip_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата TeleZip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='telezip_mid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='TeleZip MID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Посилання'),
        ),
    ]
