# Generated by Django 5.2.14 on 2026-06-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysistask_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва дослідження')),
                ('date_from', models.DateField(verbose_name='Період від')),
                ('date_to', models.DateField(verbose_name='Період до')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('collecting', 'Збір'), ('enriching', 'Збагачення'), ('classifying', 'Класифікація'), ('deduplicating', 'Дедуплікація'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Копія конфігурації задачі на момент запуску', verbose_name='Знімок параметрів')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Розбивки: по місяцях, регіонах, типах, сторонах', verbose_name='Агреговані результати')),
                ('posts_collected', models.PositiveIntegerField(default=0, verbose_name='Зібрано постів')),
                ('posts_relevant', models.PositiveIntegerField(default=0, verbose_name='Релевантних постів')),
                ('events_total', models.PositiveIntegerField(default=0, verbose_name='Усього подій')),
                ('events_corroborated', models.PositiveIntegerField(default=0, verbose_name='Підтверджених подій')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analysis.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Дослідження (запуск)',
                'verbose_name_plural': 'Дослідження (запуски)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analysis.researchrun', verbose_name='Запуск'),
        ),
        migrations.AddField(
            model_name='post',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.researchrun', verbose_name='Запуск'),
        ),
    ]
