# Generated by Django 5.2.14 on 2026-06-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_researchrun_event_run_post_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва (канонічна)')),
                ('kind', models.CharField(blank=True, choices=[('республіка', 'Республіка'), ('область', 'Область'), ('край', 'Край'), ('місто', 'Місто федерального значення'), ('ао', 'Автономний округ/область')], max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': "Суб'єкт РФ",
                'verbose_name_plural': "Суб'єкти РФ",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='settlement',
            field=models.CharField(blank=True, max_length=160, verbose_name='Населений пункт'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=128, verbose_name='Регіон (сирий)'),
        ),
        migrations.AddField(
            model_name='event',
            name='region_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analysis.region', verbose_name="Суб'єкт РФ"),
        ),
        migrations.CreateModel(
            name='RegionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=200, unique=True, verbose_name='Варіант (аліас)')),
                ('settlement', models.CharField(blank=True, max_length=160, verbose_name='Населений пункт')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.region', verbose_name="Суб'єкт РФ")),
            ],
            options={
                'verbose_name': 'Аліас регіону',
                'verbose_name_plural': 'Аліаси регіонів',
            },
        ),
    ]
