# Generated by Django 5.2.14 on 2026-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_region_event_settlement_alter_event_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reach',
            field=models.BigIntegerField(default=0, help_text='Сумарна к-сть підписників унікальних каналів події', verbose_name='Охоплення'),
        ),
    ]
