# Generated by Django 5.2.14 on 2026-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_event_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='telezip_unique',
            field=models.BooleanField(default=False, help_text='Якщо ВИМКНЕНО — збирати ВСІ репости (повне охоплення, але більше даних). Якщо увімкнено — TeleZip віддає по одній копії (менше даних, занижене охоплення).', verbose_name='TeleZip unique (згортати репости)'),
        ),
    ]
