# Generated by Django 5.2.14 on 2026-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysistask_telezip_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dedup_group',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID кластера після hash+fuzzy преклстеру (корінь групи)', null=True, verbose_name='Група дедупу'),
        ),
    ]
