# Generated by Django 5.2.14 on 2026-06-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_post_dedup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sides',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Назва (канонічна)')),
                ('category', models.CharField(choices=[('nationality', 'Національність'), ('status', 'Статус (мігрант/місцеві)'), ('religion', 'Релігія'), ('role', 'Роль/професія/вік'), ('group', 'Організація/спільнота'), ('other', 'Інше')], db_index=True, default='other', max_length=20, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='uniq_tag_name_category')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='analysis.tag', verbose_name='Сторони/теги'),
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=120, unique=True, verbose_name='Варіант (аліас)')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analysis.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Аліас тега',
                'verbose_name_plural': 'Аліаси тегів',
            },
        ),
        migrations.DeleteModel(
            name='NationalityAlias',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
