# Generated by Django 5.2.14 on 2026-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_remove_event_sides_tag_event_tags_tagalias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistask',
            name='channels_only',
        ),
        migrations.AddField(
            model_name='analysistask',
            name='collect_chunk_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Період дробиться на чанки для TeleZip (ліміт ~2 хв/запит). Не впливає на вікно дедупу — воно працює на весь період.', verbose_name='Розмір чанка збору (днів)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='search_comments',
            field=models.BooleanField(default=False, help_text='Включати коментарі/повідомлення чатів', verbose_name='Шукати по коментарях'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='search_posts',
            field=models.BooleanField(default=True, help_text='Включати пости каналів', verbose_name='Шукати по постах'),
        ),
    ]
