# Generated by Django 5.2.15 on 2026-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_analysistask_channels_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='conflict_type',
        ),
        migrations.RemoveField(
            model_name='conflicttypealias',
            name='conflict_type',
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('nationality', 'Національність'), ('status', 'Статус (мігрант/місцеві)'), ('religion', 'Релігія'), ('role', 'Роль/професія/вік'), ('group', 'Організація/спільнота'), ('conflict', 'Тип конфлікту'), ('other', 'Інше')], db_index=True, default='other', max_length=20, verbose_name='Категорія'),
        ),
        migrations.DeleteModel(
            name='ConflictType',
        ),
        migrations.DeleteModel(
            name='ConflictTypeAlias',
        ),
    ]
