# Generated by Django 5.2.15 on 2026-06-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_remove_event_conflict_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Від')),
                ('date_to', models.DateField(verbose_name='До')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Збирається'), ('done', 'Зібрано'), ('failed', 'Помилка'), ('split', 'Розбито на менші')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Спроб')),
                ('posts_collected', models.PositiveIntegerField(default=0, verbose_name='Зібрано постів')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Захоплено')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Чанк збору',
                'verbose_name_plural': 'Чанки збору',
                'ordering': ['date_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='researchrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Збір (job)', 'verbose_name_plural': 'Збори (jobs)'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='analysis_po_task_id_fb7786_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='run',
        ),
        migrations.RemoveField(
            model_name='post',
            name='run',
        ),
        migrations.AddField(
            model_name='post',
            name='stage',
            field=models.CharField(choices=[('collected', 'Зібрано'), ('enriched', 'Збагачено'), ('preclustered', 'Прекластеризовано'), ('classified', 'Класифіковано'), ('deduped', 'Дедупльовано'), ('done', 'Готово'), ('failed', 'Помилка')], db_index=True, default='collected', max_length=16, verbose_name='Стадія конвеєра'),
        ),
        migrations.AddField(
            model_name='post',
            name='stage_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Спроб стадії'),
        ),
        migrations.AddField(
            model_name='post',
            name='stage_error',
            field=models.TextField(blank=True, verbose_name='Помилка стадії'),
        ),
        migrations.AddField(
            model_name='post',
            name='stage_locked_at',
            field=models.DateTimeField(blank=True, help_text="Час claim'у; звільняється після успіху або таймауту", null=True, verbose_name='Захоплено воркером'),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='chunk_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Скільки днів за один запит TeleZip (адаптивно зменшується при падіннях)', verbose_name='Розмір чанку (днів)'),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='min_chunk_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Мін. розмір чанку (днів)'),
        ),
        migrations.AlterField(
            model_name='researchrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('collecting', 'Збір триває'), ('collected', 'Збір завершено'), ('done', 'Готово'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='researchrun',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['task', 'stage'], name='analysis_po_task_id_c3a919_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['task', 'stage', 'posted_at'], name='analysis_po_task_id_047ebc_idx'),
        ),
        migrations.AddField(
            model_name='collectchunk',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='analysis.researchrun', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='collectchunk',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_chunks', to='analysis.analysistask', verbose_name='Задача'),
        ),
        migrations.AddIndex(
            model_name='collectchunk',
            index=models.Index(fields=['task', 'status'], name='analysis_co_task_id_121882_idx'),
        ),
        migrations.AddIndex(
            model_name='collectchunk',
            index=models.Index(fields=['task', 'date_from', 'date_to'], name='analysis_co_task_id_b02695_idx'),
        ),
    ]
