# Generated by Django 5.2.15 on 2026-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_collectchunk_alter_researchrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='closed_tag_categories',
            field=models.JSONField(blank=True, default=list, help_text='Категорії, що канонізуються лише із сід-списку (інші — відкритий словник). Для етнічної задачі: ["nationality","conflict"]. Порожньо — усі відкриті.', verbose_name='Закриті категорії тегів'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='dedup_judge_prompt',
            field=models.TextField(blank=True, help_text='Системний промпт LLM-судді «одна подія чи різні». Порожньо — дефолтний.', verbose_name='Промпт дедуп-судді'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='generic_sides',
            field=models.JSONField(blank=True, default=list, help_text='«Парасолькові» сторони, що НЕ вважаються спільним сигналом у дедупі (напр. мігрант/місцевий). Порожньо — дефолтний набір.', verbose_name='Генеричні сторони'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='geo_enabled',
            field=models.BooleanField(default=True, help_text='Чи визначати регіон/населений пункт події. Вимкни для не-географічних задач.', verbose_name="Геолокація (суб'єкт+місто)"),
        ),
    ]
