# Generated by Django 5.2.15 on 2026-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_analysistask_closed_tag_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=80, verbose_name='Назва')),
                ('closed', models.BooleanField(default=False, help_text='Якщо так — теги цієї категорії беруться лише з сід-списку, нові не створюються.', verbose_name='Закрита (лише сід-список)')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія тегів',
                'verbose_name_plural': 'Категорії тегів',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(db_index=True, default='other', max_length=32, verbose_name='Категорія (key)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='tag_categories',
            field=models.ManyToManyField(blank=True, help_text='Які категорії тегів класифікатор збирає з поста (схема промпта будується з них).', related_name='tasks', to='analysis.tagcategory', verbose_name='Категорії тегів'),
        ),
    ]
