# Generated by Django 5.2.15 on 2026-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_tagcategory_alter_tag_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='hint',
            field=models.CharField(blank=True, help_text='Що писати в цю категорію (для відкритих). Порожньо — дефолтна підказка.', max_length=300, verbose_name='Підказка для промпта'),
        ),
    ]
