# Generated by Django 5.2.15 on 2026-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_tagcategory_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='review_enabled',
            field=models.BooleanField(default=False, help_text='Доганяти готові події дорожчою моделлю: відсів хибнопозитивів, злиття дублів, фікс гео/полів.', verbose_name='Фінальний AI-аудит'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='review_model',
            field=models.CharField(blank=True, default='anthropic/claude-sonnet-4', help_text='Дорожча LLM для фінального аудиту (OpenRouter).', max_length=100, verbose_name='Модель аудиту'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='review_prompt',
            field=models.TextField(blank=True, help_text='Системний промпт аудитора. Порожньо — дефолтний.', verbose_name='Промпт аудиту'),
        ),
        migrations.AddField(
            model_name='event',
            name='review_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблоковано аудитом о'),
        ),
        migrations.AddField(
            model_name='event',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Нотатки аудиту'),
        ),
        migrations.AddField(
            model_name='event',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Очікує аудиту'), ('approved', 'Схвалено'), ('rejected', 'Відхилено (буде видалено)')], db_index=True, default='pending', max_length=12, verbose_name='Статус аудиту'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проаудитовано о'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['task', 'review_status'], name='analysis_ev_task_id_cbdabc_idx'),
        ),
    ]
