# Generated by Django 5.2.15 on 2026-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_analysistask_review_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectchunk',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Експоненційний backoff для транзієнтних помилок мережі/TeleZip', null=True, verbose_name='Наступна спроба не раніше'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='review_model',
            field=models.CharField(blank=True, default='anthropic/claude-sonnet-4.6', help_text='Дорожча LLM для фінального аудиту (OpenRouter).', max_length=100, verbose_name='Модель аудиту'),
        ),
    ]
