# Generated by Django 5.2.15 on 2026-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_collectchunk_next_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bot_farm_score',
            field=models.FloatField(default=0.0, help_text='0..1: чим вище — тим більше бот-ознак (URL-інжекти, дублювання, спред).', verbose_name='Бот-ферма score'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_bot_farm',
            field=models.BooleanField(db_index=True, default=False, help_text='Подія поширювалась SEO/бот-сіткою (URL-інжекти, дублювання тексту, розтяг у часі або шаблонна мікроваріація). Виявляється евристикою — див. `manage.py detect_bot_farms`.', verbose_name='Бот-ферма / інфо-операція'),
        ),
    ]
