# Generated by Django 5.2.15 on 2026-06-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_event_bot_farm_score_event_is_bot_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='channel_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Скільки УНІКАЛЬНИХ каналів опублікували цю подію.', verbose_name='Кількість каналів'),
        ),
    ]
