# Generated by Django 5.2.15 on 2026-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_event_channel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attacker_tags',
            field=models.ManyToManyField(blank=True, help_text='Лише nationality-теги; задайте після ручної верифікації.', related_name='events_as_attacker', to='analysis.tag', verbose_name='Етнос — нападник'),
        ),
        migrations.AddField(
            model_name='event',
            name='victim_tags',
            field=models.ManyToManyField(blank=True, help_text='Лише nationality-теги; задайте після ручної верифікації.', related_name='events_as_victim', to='analysis.tag', verbose_name='Етнос — жертва'),
        ),
    ]
