# Generated by Django 5.2.15 on 2026-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_event_attacker_tags_event_victim_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='population',
            field=models.BigIntegerField(blank=True, help_text='К-сть мешканців (для нормалізації подій per-100k).', null=True, verbose_name='Населення'),
        ),
    ]
