# Generated by Django 5.2.15 on 2026-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_analysistask_pipeline_monitor_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelezipSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(unique=True)),
                ('leased_until', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'TeleZip slot',
                'verbose_name_plural': 'TeleZip slots',
                'db_table': 'analysis_telezip_slot',
            },
        ),
        migrations.RenameIndex(
            model_name='monitorchat',
            new_name='analysis_mo_task_id_b66777_idx',
            old_name='analysis_mo_task_id_act_idx',
        ),
        migrations.AlterField(
            model_name='monitorchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
