# Generated by Django 5.2.15 on 2026-06-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_telezipslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attacker_tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='victim_tags',
        ),
    ]
