# Generated by Django 5.2.15 on 2026-06-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_remove_event_attacker_tags_remove_event_victim_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_corroborated',
        ),
    ]
