# Generated by Django 5.2.15 on 2026-06-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_remove_event_is_corroborated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bot_farm_score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_bot_farm',
        ),
    ]
