# Generated by Django 5.2.15 on 2026-06-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_remove_event_bot_farm_score_remove_event_is_bot_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='drop_linked_comments',
            field=models.BooleanField(default=False, help_text="TeleZip повертає коментарі із закритих груп-обговорень з префіксом 'linked:' у назві каналу. Увімкни, щоб такі пости не потрапляли в конвеєр подій (відсіюються на стадії precluster).", verbose_name='Відсівати linked-коментарі'),
        ),
    ]
