# Generated by Django 5.2.15 on 2026-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_analysistask_drop_linked_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='min_channel_subscribers',
            field=models.PositiveIntegerField(default=0, help_text='0 = без фільтра. Якщо >0 — пости з ЕНРІЧЕНИХ каналів, де підписників менше за це число, відсіюються на precluster (не йдуть у classify/dedup). Прибирає бот-ферму: одну історію, накручену по тисячах мікроканалів.', verbose_name='Мін. підписників каналу'),
        ),
    ]
