# Generated by Django 5.2.15 on 2026-06-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_analysistask_min_channel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('channel', 'Канал (мовлення)'), ('chat', 'Чат/група (обговорення)'), ('discussion', 'Група-обговорення каналу (linked)'), ('unknown', 'Невідомо')], db_index=True, max_length=16, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='channel',
            name='directory_classified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Класифіковано (директорія)'),
        ),
        migrations.AddField(
            model_name='channel',
            name='directory_focus',
            field=models.CharField(blank=True, max_length=300, verbose_name='Фокус (1 речення)'),
        ),
        migrations.AddField(
            model_name='channel',
            name='directory_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Сире рішення агента: confidence, reason, сирі region/topics.', verbose_name='Метадані класифікації'),
        ),
        migrations.AddField(
            model_name='channel',
            name='discusses_problems',
            field=models.BooleanField(blank=True, db_index=True, help_text='Чи реально обговорюють суспільні/політичні/етнічні проблеми РФ', null=True, verbose_name='Обговорює проблеми РФ'),
        ),
        migrations.AddField(
            model_name='channel',
            name='region_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='analysis.region', verbose_name="Суб'єкт РФ (канонічний)"),
        ),
        migrations.AddField(
            model_name='channel',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Список тем (новини, етнічне, політика, локал-чат, барахолка…)', verbose_name='Теми'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['region_subject', 'discusses_problems'], name='analysis_ch_region__f14e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['chat_type', 'subscribers'], name='analysis_ch_chat_ty_12f483_idx'),
        ),
    ]
