# Generated by Django 5.2.15 on 2026-06-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_channel_chat_type_channel_directory_classified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_channel_repost',
            field=models.BooleanField(db_index=True, default=False, help_text='True = це повідомлення з КАНАЛУ (авто-форвард linked-каналу або переслане), а не оригінальна репліка учасника. ІГНОРУВАТИ при аналізі активності чату. Визначається збігом content_hash з постом каналу.', verbose_name='Репост каналу в чаті'),
        ),
    ]
