# Generated by Django 5.2.15 on 2026-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_post_is_channel_repost'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['task', 'stage', 'posted_at', 'channel'], name='analysis_po_task_id_86ae4f_idx'),
        ),
    ]
