# Generated by Django 5.2.15 on 2026-06-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_post_analysis_po_task_id_86ae4f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='День')),
                ('total', models.IntegerField(default=0, verbose_name='Усіх повідомлень')),
                ('relevant', models.IntegerField(default=0, verbose_name='Критика')),
                ('reposts', models.IntegerField(default=0, verbose_name='Авто-репости каналу')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='analysis.channel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='analysis.analysistask')),
            ],
            options={
                'verbose_name': 'Денна статистика каналу',
                'verbose_name_plural': 'Денні статистики каналів',
                'indexes': [models.Index(fields=['task', 'date'], name='analysis_ch_task_id_d9dd92_idx'), models.Index(fields=['channel', 'date'], name='analysis_ch_channel_4ffdbe_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'channel', 'date'), name='uniq_chan_daily_stat')],
            },
        ),
    ]
