# Generated by Django 5.2.15 on 2026-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_channeldailystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldailystat',
            name='telezip_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Усіх повідомлень (TeleZip, авторитетно)'),
        ),
        migrations.AlterField(
            model_name='channeldailystat',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Усіх повідомлень (із зібраних постів)'),
        ),
    ]
