# Generated by Django 5.2.15 on 2026-07-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_channeldailystat_telezip_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region_subject',
            field=models.ForeignKey(blank=True, help_text='Копія channel.region_subject для прямого GROUP BY і per-100k без JOIN (спільний аналітичний контракт подій і критики — див. services/metrics.py).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.region', verbose_name="Суб'єкт РФ (денормалізовано)"),
        ),
    ]
