# Generated by Django 5.2.15 on 2026-07-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_post_region_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='analysis.tag', verbose_name='Теги'),
        ),
    ]
