# Generated by Django 5.2.15 on 2026-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('collecting', 'Збір триває'), ('collected', 'Збір завершено'), ('awaiting_agent', 'Чекає агента (тегування)'), ('done', 'Готово'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
