# Generated by Django 5.2.15 on 2026-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_alter_researchrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='mon_max_len',
            field=models.PositiveSmallIntegerField(default=600, help_text='Довші — найімовірніше пости/репости каналу, не коментарі людей.', verbose_name='Фільтр: макс. довжина'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='mon_min_len',
            field=models.PositiveSmallIntegerField(default=25, help_text='Коротші повідомлення відсіюються як шум (емодзі, «+1»).', verbose_name='Фільтр: мін. довжина коментаря'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='prescreen_model',
            field=models.CharField(blank=True, help_text='Дешева модель для «так/ні» відсіву. Порожньо — дефолт із settings.', max_length=100, verbose_name='Прескрін: модель (OpenRouter)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='prescreen_prompt',
            field=models.TextField(blank=True, help_text='Порожньо — стандартний compact-промпт із analysis/pilot/prompts.py.', verbose_name='Прескрін: системний промпт'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='tagger_prompt',
            field=models.TextField(blank=True, help_text='Іде в SYSTEM_PROMPT.md батчів для Claude-агентів. Порожньо — стандартний TAGGER_SYSTEM_PROMPT із prompts.py.', verbose_name='Тегування: системний промпт агента'),
        ),
    ]
