# Generated by Django 5.2.15 on 2026-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_analysistask_mon_max_len_analysistask_mon_min_len_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='agent_review_prompt',
            field=models.TextField(blank=True, help_text="Іде агентам у SYSTEM_PROMPT.md рев'ю-батчів запуску (статус «Чекає агента»). Порожньо — стандартний EVENT_REVIEW_PROMPT.md із analysis/pilot/.", verbose_name='Агент-аудит: промпт'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='review_enabled',
            field=models.BooleanField(default=False, help_text='Воркер проганяє готові події ДЕШЕВОЮ моделлю: грубий відсів хибнопозитивів. Якість добиває агент-аудит (етап нижче).', verbose_name='Авто-аудит: перший прохід'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='review_model',
            field=models.CharField(blank=True, default='google/gemini-2.5-flash', help_text='Дешева LLM (OpenRouter) для першого проходу — напр. gemini-flash.', max_length=100, verbose_name='Авто-аудит: модель'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='review_prompt',
            field=models.TextField(blank=True, help_text='Системний промпт авто-аудитора. Порожньо — дефолтний.', verbose_name='Авто-аудит: промпт'),
        ),
    ]
