# Generated by Django 5.2.15 on 2026-07-06 08:10

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_analysistask_agent_review_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='agent_review_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_agent_review_prompt, help_text='Зберігається в задачі й береться звідси при запуску аудиту. Порожньо — стандартний EVENT_REVIEW_PROMPT.md (запасний варіант).', verbose_name='Агент-аудит: промпт'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='prescreen_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_prescreen_prompt, help_text='Зберігається в задачі й береться звідси при запуску. Порожньо — стандартний із коду (запасний варіант).', verbose_name='Прескрін: системний промпт'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='tagger_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_tagger_prompt, help_text='Зберігається в задачі; йде агентам у SYSTEM_PROMPT.md пачок. Порожньо — стандартний із коду (запасний варіант).', verbose_name='Тегування: системний промпт агента'),
        ),
    ]
