# Generated by Django 5.2.15 on 2026-07-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_alter_analysistask_agent_review_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Збирати лише пости цими мовами, напр. ["ru"] — інакше в вибірку лізуть інші мови. Порожньо: пошук подій — без фільтра; моніторинг — автоматично "ru".', verbose_name='Мови (фільтр пошуку TeleZip)'),
        ),
    ]
