# Generated by Django 5.2.15 on 2026-07-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_alter_analysistask_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistask',
            name='closed_tag_categories',
        ),
    ]
