# Generated by Django 5.2.15 on 2026-07-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_remove_analysistask_closed_tag_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistask',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='analysistask',
            name='date_to',
        ),
    ]
