# Generated by Django 5.2.15 on 2026-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0042_remove_analysistask_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='geo_enabled',
            field=models.BooleanField(default=True, help_text="Увімкнено: модель витягує з тексту суб'єкт РФ і місто (якщо в тексті нема — береться «домашній» регіон каналу), сирі назви зводяться до довідника суб'єктів. Вимкнено (моніторинг): регіон = регіон чату, в якому написано коментар.", verbose_name="Геолокація (суб'єкт+місто)"),
        ),
    ]
