# Generated by Django 5.2.15 on 2026-07-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0043_alter_analysistask_geo_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistask',
            name='relevance_field',
        ),
    ]
