# Generated by Django 5.2.15 on 2026-07-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0044_remove_analysistask_relevance_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='telezip_query',
            field=models.TextField(help_text='Запит у синтаксисі TeleZip (text=...). <a href="https://docs.google.com/document/d/1oKag8XfmpOnKapbkayRZzq8JHbpB8GaKvSgC1judnvg/edit?tab=t.0" target="_blank" rel="noopener">Документація TeleZip ↗</a>', verbose_name='Пошуковий запит TeleZip'),
        ),
    ]
