# Generated by Django 5.2.15 on 2026-07-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0045_alter_analysistask_telezip_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='pipeline',
            field=models.CharField(choices=[('events', 'Події (enrich→precluster→classify→dedup)'), ('monitor', 'Моніторинг думок (filter→prescreen→tag)'), ('research', 'Тематичне дослідження (канали→рубрики→агенти→події)')], db_index=True, default='events', help_text='events-воркери та monitor-воркери беруть лише «свої» задачі — пост задачі ніколи не потрапить у чужу стадію.', max_length=12, verbose_name='Конвеєр'),
        ),
        migrations.CreateModel(
            name='ResearchRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Напр. E2, C3, P1.', verbose_name='Ключ')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('tag_category', models.CharField(help_text='Куди класти тег події (напр. econ_event).', max_length=50, verbose_name='Категорія тегу')),
                ('tag_name', models.CharField(help_text='Канонічна назва тегу рубрики (get_or_create у цій категорії).', max_length=200, verbose_name='Тег події')),
                ('keywords', models.JSONField(default=list, help_text='Список груп: пост-кандидат, якщо БУДЬ-ЯКА група спрацювала; група = всі слова присутні. Напр. [["протест","завод"],["страйк"]].', verbose_name='Ключові слова (АБО-список І-груп)')),
                ('extra_prompt', models.TextField(blank=True, help_text='Специфічні правила рубрики, додаються до промпту агента.', verbose_name='Доповнення промпту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='analysis.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Рубрика дослідження',
                'verbose_name_plural': 'Рубрики дослідження',
                'ordering': ['order', 'key'],
                'unique_together': {('task', 'key')},
            },
        ),
    ]
