# Generated by Django 5.2.15 on 2026-07-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_alter_analysistask_pipeline_researchrubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrubric',
            name='key',
            field=models.SlugField(blank=True, help_text='Технічний ідентифікатор рубрики; авто з тегу події, якщо порожньо.', verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='researchrubric',
            name='keywords',
            field=models.JSONField(default=list, help_text='Список РЕГУЛЯРОК (ТЕМА ∧ ДІЯ): кандидат, якщо КОЖНА збіглась. Напр. ["коррупц|взятк|откат", "задержа|арест|обыск"].', verbose_name='Ключові слова (АБО-список І-груп)'),
        ),
        migrations.AlterField(
            model_name='researchrubric',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва'),
        ),
    ]
