# Generated by Django 5.2.15 on 2026-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_alter_researchrubric_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='dedup_group_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Пости одного інциденту в межах ±N днів вважаються тим самим.', verbose_name='Дедуп: вікно склейки (днів)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='dedup_group_fuzz',
            field=models.PositiveSmallIntegerField(default=70, help_text='Схожість підсумків (0-100) для механічної склейки очевидних дублів. Вище = обережніше (менше склеює).', verbose_name='Дедуп: поріг схожості (%)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='dedup_llm_cluster',
            field=models.BooleanField(default=True, help_text='Після механіки — агент зливає інциденти «одна подія різними словами» (як історичний скрипт). Вимкни, щоб лишити лише механіку (дешевше, але дробить дублі).', verbose_name='Дедуп: LLM-злиття інцидентів'),
        ),
    ]
