# Generated by Django 5.2.15 on 2026-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_analysistask_dedup_group_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='pipeline',
            field=models.CharField(choices=[('events', 'Події (enrich→precluster→classify→dedup)'), ('monitor', 'Моніторинг думок (filter→prescreen→tag)'), ('research', 'Тематичне дослідження (канали→рубрики→агенти→дедуп)')], db_index=True, default='events', help_text='events-воркери та monitor-воркери беруть лише «свої» задачі — пост задачі ніколи не потрапить у чужу стадію.', max_length=12, verbose_name='Конвеєр'),
        ),
    ]
