# Generated by Django 5.2.15 on 2026-07-08 14:41

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0049_alter_analysistask_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='dedup_cluster_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_cluster_prompt, help_text='Іде агенту-обʼєднувачу (SYSTEM_PROMPT_CLUSTER.md). Зберігається в задачі; порожньо — стандартний із коду.', verbose_name='Дедуп: промпт LLM-злиття'),
        ),
    ]
