# Generated by Django 5.2.15 on 2026-07-08 14:50

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_analysistask_dedup_cluster_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='research_audit_enabled',
            field=models.BooleanField(default=False, help_text='Після групування дублів у події запуск ставиться в «Чекає агента»: Claude-агенти виносять keep/reject по кожній події, ранер застосовує вердикти (reject → review_status=rejected).', verbose_name='Агент-аудит подій'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='research_audit_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_research_audit_prompt, help_text='Іде агентам у SYSTEM_PROMPT_AUDIT.md. Зберігається в задачі; порожньо — стандартний із коду.', verbose_name='Агент-аудит: промпт'),
        ),
    ]
