# Generated by Django 5.2.15 on 2026-07-09 12:07

import analysis.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_proxy_options_alter_proxy_created_at_and_more'),
        ('analysis', '0051_analysistask_research_audit_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='info_judge_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_info_judge_prompt, help_text='«Той самий факт чи інший?» — attach/new + чи оновити опис. Порожньо — стандартний із коду.', verbose_name='Зіставлення: промпт судді'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_match_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Ковзне вікно пошуку «такої самої події» відносно дати поста.', verbose_name='Зіставлення: вікно збігу (год)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_retention_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Нерелевантні done-пости старші за N діб видаляються (пости, приєднані до подій, не чіпаються).', verbose_name='Ретеншн сирих постів (днів)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_screen_model',
            field=models.CharField(blank=True, help_text='Дешева модель для фільтра релевантності + короткого опису. Порожньо — дефолт із settings.', max_length=100, verbose_name='Скрін: модель (OpenRouter)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_screen_prompt',
            field=models.TextField(blank=True, default=analysis.models._default_info_screen_prompt, help_text='Критерії теми задачі; модель повертає relevant/signature/summary/region/tags одним викликом. Порожньо — стандартний із коду.', verbose_name='Скрін: системний промпт'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_tagger_prompt',
            field=models.TextField(blank=True, help_text='Додаткові правила для блоку tags (напр. критерії тегу «гучна подія»). Додаються до скрін-промпту; схема категорій будується з «Категорії тегів». Порожньо — лише підказки категорій.', verbose_name='Скрін: правила тегування'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='info_update_summaries',
            field=models.BooleanField(default=True, help_text='Суттєві доповнення з нових постів переписують опис події. Вимкнено — опис фіксується з першого поста.', verbose_name='Жива подія (оновлювати опис)'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_post_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Час останнього приєднаного поста. Заповнює ЛИШЕ infospace-конвеєр (ковзне вікно збігу + сортування «живих» сюжетів); інші конвеєри не чіпають.', null=True, verbose_name='Останній пост'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, db_default='', help_text='Заголовок статті/RSS-item (для Telegram порожній).', max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='pipeline',
            field=models.CharField(choices=[('events', 'Події (enrich→precluster→classify→dedup)'), ('monitor', 'Моніторинг думок (filter→prescreen→tag)'), ('research', 'Тематичне дослідження (канали→рубрики→агенти→дедуп)'), ('infospace', 'Інформпростір (полінг джерел→скрін→жива подія)')], db_index=True, default='events', help_text='events-воркери та monitor-воркери беруть лише «свої» задачі — пост задачі ніколи не потрапить у чужу стадію.', max_length=12, verbose_name='Конвеєр'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stage',
            field=models.CharField(choices=[('collected', 'Зібрано'), ('enriched', 'Збагачено'), ('preclustered', 'Прекластеризовано'), ('classified', 'Класифіковано'), ('deduped', 'Дедупльовано'), ('mon_collected', 'Монітор: зібрано'), ('mon_filtered', 'Монітор: відфільтровано'), ('mon_prescreened', 'Монітор: прескрін+'), ('info_collected', 'Інформпростір: зібрано'), ('info_screened', 'Інформпростір: скрін+'), ('done', 'Готово'), ('failed', 'Помилка')], db_index=True, default='collected', max_length=16, verbose_name='Стадія конвеєра'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('telegram', 'Telegram-канал (акаунт)'), ('rss', 'RSS-стрічка'), ('web', 'Сайт (скрапінг)'), ('vk', 'VK (згодом)')], db_index=True, max_length=12, verbose_name='Тип')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('url', models.CharField(help_text='tg: @username або t.me/…; rss: URL стрічки; web: URL лістинг-сторінки розділу.', max_length=500, verbose_name='Ідентифікатор (URL)')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='Мова')),
                ('scraper_key', models.CharField(blank=True, help_text='Ключ у реєстрі SCRAPERS (infospace/scrapers.py). Порожньо = автоекстракція (trafilatura) / селектори з config.', max_length=50, verbose_name='Кастомний скрапер')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Селектори discovery/extraction, max_items, backfill_limit, full_text, headers… — див. док конвеєра.', verbose_name='Конфігурація')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активне')),
                ('poll_interval_sec', models.PositiveIntegerField(default=600, verbose_name='Інтервал полінгу (сек)')),
                ('next_poll_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Черга полінгу; бекоф при збоях. «Опитати зараз» = поставити now.', verbose_name='Наступний полінг')),
                ('locked_at', models.DateTimeField(blank=True, help_text="Час claim'у; звільняється після проходу або таймауту.", null=True, verbose_name='Захоплено воркером')),
                ('state', models.JSONField(blank=True, default=dict, help_text='Приватний стан адаптера свого kind: tg last_msg_id / rss etag…', verbose_name='Watermark адаптера')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній успіх')),
                ('last_error', models.TextField(blank=True, verbose_name='Остання помилка')),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, verbose_name='Збоїв поспіль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('region_subject', models.ForeignKey(blank=True, help_text='Регіон джерела; денормалізується в Post при вставці (per-100k).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='analysis.region', verbose_name="Суб'єкт РФ")),
                ('tg_account', models.ForeignKey(blank=True, help_text='Яким акаунтом полити цей канал. Порожньо — пул (round-robin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='accounts.telegramaccount', verbose_name='Telegram-акаунт')),
            ],
            options={
                'verbose_name': 'Джерело (інформпростір)',
                'verbose_name_plural': 'Джерела (інформпростір)',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Звідки зібрано пост у infospace-конвеєрі; для TeleZip-конвеєрів NULL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.source', verbose_name='Джерело (інформпростір)'),
        ),
        migrations.CreateModel(
            name='SourceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Зніми галочку, щоб виключити джерело з наступних зборів цієї задачі, не видаляючи історичні дані.', verbose_name='Активна')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Менше = вище у списку.', verbose_name='Пріоритет')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='analysis.source', verbose_name='Джерело')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_subscriptions', to='analysis.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Підписка на джерело',
                'verbose_name_plural': 'Підписки на джерела',
                'ordering': ['task', 'priority', 'source__name'],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active', 'next_poll_at'], name='analysis_so_is_acti_d2a1cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('kind', 'url'), name='uniq_source_kind_url'),
        ),
        migrations.AddIndex(
            model_name='sourcesubscription',
            index=models.Index(fields=['task', 'is_active'], name='analysis_so_task_id_ab38c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcesubscription',
            unique_together={('task', 'source')},
        ),
    ]
