# Generated by Django 5.2.16 on 2026-07-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_proxy_options_alter_proxy_created_at_and_more'),
        ('analysis', '0052_analysistask_info_judge_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='tg_account',
            field=models.ForeignKey(blank=True, help_text='Яким акаунтом полити цей канал. Порожньо — перший авторизований (ротація по пулу — Phase 4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='accounts.telegramaccount', verbose_name='Telegram-акаунт'),
        ),
    ]
