# Generated by Django 5.2.16 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_alter_source_tg_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_healthcheck_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання самоперевірка'),
        ),
        migrations.AddField(
            model_name='source',
            name='quality_note',
            field=models.CharField(blank=True, help_text='Чому 🟡 підозра (напр. «discovery: 0 лінків»).', max_length=200, verbose_name='Нотатка якості'),
        ),
        migrations.AddField(
            model_name='source',
            name='quality_ok',
            field=models.BooleanField(db_index=True, default=True, help_text='False = 🟡 підозра: dry-run дав 0 елементів або порожній текст (сайт переверстали / селектор зламано). Ставить info_healthcheck.', verbose_name='Якість ок'),
        ),
    ]
