# Generated by Django 5.2.16 on 2026-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0054_source_last_healthcheck_at_source_quality_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='info_max_age_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Елементи, старші за N діб (за датою публікації), НЕ потрапляють у конвеєр — монітор бере лише свіже. Захищає і від хибної дати extraction / архівних сторінок.', verbose_name='Свіжість: макс. вік новини (днів)'),
        ),
    ]
