# Generated by Django 5.2.16 on 2026-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0056_rename_source_state_poll_cursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, verbose_name='Значення')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Опис')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
                'ordering': ['key'],
            },
        ),
    ]
