# Generated by Django 5.2.16 on 2026-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_publishconfig_publishedevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishconfig',
            name='region_subject',
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Порожньо = усі регіони; інакше подія має бути з ОДНОГО з обраних.', related_name='publish_configs', to='analysis.region', verbose_name="Суб'єкти РФ"),
        ),
    ]
