# Generated by Django 5.2.16 on 2026-07-17 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_remove_publishconfig_region_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Не-суперюзери бачать в адмінці лише свої задачі.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Не-суперюзери бачать в адмінці лише свої профілі.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_publish_configs', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
    ]
