# Generated by Django 5.2.16 on 2026-07-17 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0061_assign_owner_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openrouter_key', models.CharField(blank=True, help_text='Персональний ключ для задач/публікацій/звітів цього юзера. Порожньо = глобальний ключ із env (OPENROUTER_API_KEY).', max_length=200, verbose_name='OpenRouter API-ключ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача (LLM-ключ)',
                'verbose_name_plural': 'Профілі користувачів (LLM-ключі)',
            },
        ),
    ]
