# Generated by Django 5.2.17 on 2026-08-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_app_version_and_more'),
        ('analysis', '0062_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorchat',
            name='tg_account',
            field=models.ForeignKey(blank=True, help_text='Яким акаунтом читаємо цей чат. Резолв юзернейма має добовий ліміт (~200/акаунт) і кешується В СЕСІЇ того акаунта, що резолвив, — тож чат треба читати ТИМ САМИМ акаунтом, інакше резолв платиться заново.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_chats', to='accounts.telegramaccount', verbose_name='Акаунт збору'),
        ),
    ]
