# Generated by Django 5.2.17 on 2026-08-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0063_monitorchat_tg_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Початок періоду')),
                ('period_end', models.DateField(verbose_name='Кінець періоду')),
                ('id_lo', models.BigIntegerField(verbose_name='id на початку періоду')),
                ('id_hi', models.BigIntegerField(verbose_name='id у кінці періоду')),
                ('n_requested', models.PositiveIntegerField(default=0, verbose_name='Запитано id')),
                ('n_returned', models.PositiveIntegerField(default=0, verbose_name='Повернуто повідомлень')),
                ('n_text', models.PositiveIntegerField(default=0, verbose_name='З них із текстом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='analysis.channel', verbose_name='Чат')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='analysis.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вибірка (вікно)',
                'verbose_name_plural': 'Вибірки (вікна)',
                'ordering': ['-period_start', 'channel_id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'channel', 'period_start'), name='uniq_sample_task_channel_period')],
            },
        ),
    ]
