# Generated by Django 5.2.17 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0064_monitorsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsample',
            name='n_user',
            field=models.PositiveIntegerField(default=0, help_text='Решта — автопересилки постів каналу в групу обговорень (анкери, під якими пишуть коментарі). У групі новинного каналу вони можуть давати 99% потоку, тому «повідомлень на добу» без цієї поправки міряє активність КАНАЛУ, а не людей.', verbose_name='З них написані людьми'),
        ),
    ]
