# Generated by Django 5.2.17 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0065_monitorsample_n_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='prescreen_enabled',
            field=models.BooleanField(default=True, help_text='Дешевий «так/ні» відсів перед тегуванням. Він різав обсяг у 5-10 разів, коли на вході був СУЦІЛЬНИЙ потік. При ВИБІРКОВОМУ зборі обсяг і так малий, а recall прескріну ~85% — тобто кожен сьомий критичний коментар мовчки стає «нерелевантним» і занижує чисельник метрики. Для вибіркових задач вимикати.', verbose_name='Прескрін: увімкнено'),
        ),
    ]
