# Generated by Django 5.2.17 on 2026-08-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_app_version_and_more'),
        ('analysis', '0066_analysistask_prescreen_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='access',
            field=models.CharField(blank=True, choices=[('public', 'Публічний'), ('invite', 'За інвайт-лінком'), ('closed', 'Закритий'), ('dead', 'Мертвий/видалений')], db_index=True, max_length=16, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='channel',
            name='activity_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активність міряли'),
        ),
        migrations.AddField(
            model_name='channel',
            name='check_error',
            field=models.CharField(blank=True, help_text='Чому не вдалося: приватний, бан, немає історії, мертвий юзернейм.', max_length=200, verbose_name='Помилка перевірки'),
        ),
        migrations.AddField(
            model_name='channel',
            name='comments_open',
            field=models.BooleanField(blank=True, db_index=True, help_text='Канал: має linked-групу обговорення. Чат: приймає повідомлення. None = ще не перевіряли (перевіряє Telethon, не TGStat).', null=True, verbose_name='Коментарі відкриті'),
        ),
        migrations.AddField(
            model_name='channel',
            name='human_msgs_per_day',
            field=models.FloatField(blank=True, help_text='Без автопересилок каналу — головна метрика відбору джерела.', null=True, verbose_name='Людських повідомлень/добу'),
        ),
        migrations.AddField(
            model_name='channel',
            name='invite_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Інвайт-лінк'),
        ),
        migrations.AddField(
            model_name='channel',
            name='joined_by',
            field=models.ForeignKey(blank=True, help_text='Резолв кешується в сесії ТОГО акаунта, що резолвив, — читати чат треба ним же.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_channels', to='accounts.telegramaccount', verbose_name='Резолвив/вступав акаунт'),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_post_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останнє повідомлення'),
        ),
        migrations.AddField(
            model_name='channel',
            name='linked_chat',
            field=models.ForeignKey(blank=True, help_text='Канал -> його linked-група (там і лежать коментарі). Зворотний бік звʼязку (група -> чий це канал) — related_name linked_from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='analysis.channel', verbose_name='Група обговорення'),
        ),
        migrations.AddField(
            model_name='channel',
            name='msgs_per_day',
            field=models.FloatField(blank=True, help_text='З різниці id. УВАГА: рахує і автопересилки постів каналу.', null=True, verbose_name='Повідомлень/добу (сирих)'),
        ),
        migrations.AddField(
            model_name='channel',
            name='participants_visible',
            field=models.BooleanField(blank=True, help_text='ChannelFull.can_view_participants: чи можна прочитати склад учасників.', null=True, verbose_name='Список учасників відкритий'),
        ),
        migrations.AddField(
            model_name='channel',
            name='settlement',
            field=models.CharField(blank=True, db_index=True, help_text="Місто/райцентр, до якого прив'язаний канал. Той самий тип і назва, що в Event.settlement і RegionAlias.settlement — канонізація спільна.", max_length=160, verbose_name='Населений пункт'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['settlement', 'comments_open'], name='analysis_ch_settlem_fde7a7_idx'),
        ),
    ]
