# Generated by Django 5.2.17 on 2026-09-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0067_channel_access_channel_activity_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='search_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Глибина пошуку, діб'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='search_limit_per_term',
            field=models.PositiveSmallIntegerField(default=100, help_text='У дуже жвавому чаті число влучень буде впертим у стелю — це «≥ стелі», а не точна кількість.', verbose_name='Стеля влучень на слово'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='search_terms',
            field=models.TextField(blank=True, help_text='Telegram НЕ вміє OR — кожне слово це окремий запит до кожного чату. Тому сміттєві слова сюди класти дорого: вартість лінійна від їх кількості (слів × чатів запитів на прогін).', verbose_name='Слова пошуку (по одному в рядок)'),
        ),
        migrations.AddField(
            model_name='monitorchat',
            name='last_searched_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Конвеєр tgsearch: коли цей чат востаннє обшукували. Порожньо = ще жодного разу.', null=True, verbose_name='Останній TG-пошук'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='pipeline',
            field=models.CharField(choices=[('events', 'Події (enrich→precluster→classify→dedup)'), ('monitor', 'Моніторинг думок (filter→prescreen→tag)'), ('research', 'Тематичне дослідження (канали→рубрики→агенти→дедуп)'), ('infospace', 'Інформпростір (полінг джерел→скрін→жива подія)'), ('tgsearch', 'Пошук у чатах через Telegram (пошук→фільтр→теги→подія)')], db_index=True, default='events', help_text='events-воркери та monitor-воркери беруть лише «свої» задачі — пост задачі ніколи не потрапить у чужу стадію.', max_length=12, verbose_name='Конвеєр'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stage',
            field=models.CharField(choices=[('collected', 'Зібрано'), ('enriched', 'Збагачено'), ('preclustered', 'Прекластеризовано'), ('classified', 'Класифіковано'), ('deduped', 'Дедупльовано'), ('mon_collected', 'Монітор: зібрано'), ('mon_filtered', 'Монітор: відфільтровано'), ('mon_prescreened', 'Монітор: прескрін+'), ('tgs_collected', 'TG-пошук: знайдено'), ('tgs_screened', 'TG-пошук: релевантне'), ('tgs_tagged', 'TG-пошук: протеговано'), ('info_collected', 'Інформпростір: зібрано'), ('info_screened', 'Інформпростір: скрін+'), ('done', 'Готово'), ('failed', 'Помилка')], db_index=True, default='collected', max_length=16, verbose_name='Стадія конвеєра'),
        ),
    ]
