# Generated by Django 5.2.17 on 2026-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0068_analysistask_search_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='stream_interval_min',
            field=models.PositiveSmallIntegerField(default=3, help_text='Один полінг чату = один запит, навіть якщо нових повідомлень нема. Тому вартість лінійна від частоти, а ризик FloodWait — від того, СКІЛЬКИ чатів висить на одному акаунті (тримай 1 чат = 1 акаунт).', verbose_name='Стрім: інтервал полінгу, хв'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='stream_media_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID, куди пересилати фото/відео з чатів, позначених «Пересилати медіа». Порожньо = не пересилати. Акаунти збору мають бути учасниками цього чату (пересилання йде акаунтом, не ботом: це один виклик замість «завантажити й перезалити»).', max_length=64, verbose_name='Стрім: чат для медіа'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='stream_regex',
            field=models.TextField(blank=True, help_text='Регулярні вирази (регістр не важливий). Повідомлення чату, що не збіглось із жодним, у БД не потрапляє і LLM не бачить — тому патернів може бути хоч сотня, вони безкоштовні. Порожньо = стрім вимкнено (щоб випадково не вилити весь потік чатів у скрін).', verbose_name='Стрім: патерни (по одному в рядок)'),
        ),
        migrations.AddField(
            model_name='monitorchat',
            name='forward_media',
            field=models.BooleanField(db_index=True, default=False, help_text='Пересилати ВСІ фото/відео цього чату в чат медіа задачі. Вмикай лише для головних чатів: у барахолці це тисячі файлів на добу.', verbose_name='Пересилати медіа'),
        ),
        migrations.AddField(
            model_name='monitorchat',
            name='last_streamed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Останній стрім'),
        ),
        migrations.AddField(
            model_name='monitorchat',
            name='stream_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Читати цей чат суцільно кожні N хвилин і фільтрувати регулярками задачі, замість пошуку за словами. Дає повноту й затримку в хвилини.', verbose_name='Стрім (полінг + регулярка)'),
        ),
        migrations.AddField(
            model_name='monitorchat',
            name='stream_last_msg_id',
            field=models.BigIntegerField(default=0, help_text='Останнє прочитане повідомлення. Догін іде ВІД нього (reverse), тож сплеск більший за ліміт не лишає діри. 0 = ще не читали.', verbose_name='Стрім: watermark (msg_id)'),
        ),
    ]
