# Generated by Django 5.2.17 on 2026-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0069_tgsearch_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='raw_header',
            field=models.CharField(blank=True, help_text='Хештег рубрики першим рядком, напр. «#Вибори». До нього дописується регіон події і ❗ при важливості 4-5.', max_length=120, verbose_name='Без ШІ: рубрика'),
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='raw_mode',
            field=models.BooleanField(default=False, help_text='Публікувати ОРИГІНАЛЬНИЙ текст повідомлення/поста замість переказу від ШІ. Відбір при цьому робить сам фільтр профілю (теги/регіони/статус), а LLM не викликається зовсім — нуль витрат і нуль спотворень. Поля AI-модель/AI-промпт у цьому режимі ігноруються.', verbose_name='Без ШІ: оригінал + теги'),
        ),
    ]
