# Generated by Django 5.2.17 on 2026-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0070_publish_raw_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='exclude_tags',
            field=models.ManyToManyField(blank=True, help_text='Подія з БУДЬ-ЯКИМ із цих тегів не публікується. Фільтр «Теги» вище — це АБО, тож поріг на кшталт «важливість 3+» задається саме тут: виключити важливість_1 і важливість_2.', related_name='excluded_from_publish_configs', to='analysis.tag', verbose_name='Теги-виключення'),
        ),
    ]
