# Generated by Django 5.2.17 on 2026-09-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_owner_unique_phone'),
        ('analysis', '0071_publish_exclude_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='forward_account',
            field=models.ForeignKey(blank=True, help_text='Яким акаунтом пересилати фото/відео першоджерела в канал (одразу після тексту). Акаунт МУСИТЬ бути учасником каналу. Порожньо = медіа не пересилаємо. Бот тут не годиться: file_id акаунта йому не передається, а качати файл через проксі ненадійно.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_configs', to='accounts.telegramaccount', verbose_name='Акаунт для медіа'),
        ),
    ]
