# Generated by Django 5.2.17 on 2026-09-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_owner_unique_phone'),
        ('analysis', '0072_publish_forward_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='post_as_account',
            field=models.BooleanField(default=False, help_text='Увімкнено — пост іде ВІД АКАУНТА одним повідомленням разом із фото/відео оригіналу. Вимкнено — пише бот, медіа лишається за кадром. УВАГА: підпис до медіа обрізається до 1024 символів (ліміт Telegram), повний текст доступний за посиланням у пості.', verbose_name='Постити акаунтом (з медіа)'),
        ),
        migrations.AlterField(
            model_name='publishconfig',
            name='forward_account',
            field=models.ForeignKey(blank=True, help_text='Акаунт, яким виходить пост (і медіа першоджерела в тому ж повідомленні). МУСИТЬ бути учасником каналу. Порожньо = пише бот, але тоді медіа не буде: file_id акаунта боту не передається.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_configs', to='accounts.telegramaccount', verbose_name='Акаунт публікації'),
        ),
    ]
