# Generated by Django 5.2.17 on 2026-09-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0073_publish_post_as_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.JSONField(blank=True, help_text='{kind, chat, mid} — на що послатись, щоб опублікувати фото/відео разом із постом. Окреме поле, а НЕ classification: перескрін (rescreen_task_now) чистить classification, і медіа зникало б.', null=True, verbose_name='Медіа першоджерела'),
        ),
    ]
