# Generated by Django 5.2.17 on 2026-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0074_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='max_age_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ковзне вікно по event_date (даті НОВИНИ): 0 = без обмеження. Для живого моніторингу став 1-2: інакше джерело, яке щойно підключилось, виливає в канал свою історію як свіжину (ловили 18.09: новина від 15.09 пішла в канал).', verbose_name='Не публікувати старше, діб'),
        ),
    ]
