# Generated by Django 5.2.17 on 2026-09-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0075_publish_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='allow_null_region_tags',
            field=models.ManyToManyField(blank=True, help_text="Подія без визначеного суб'єкта РФ публікується ЛИШЕ якщо має один із цих тегів. Порожньо = регіон не обов'язковий. Потрібно там, де тема прив'язана до гео (фальсифікації в наших республіках), а одна тема — ні (ДЕГ по всій РФ): на промпт тут покладатися не можна, модель ставила регіон null і тема проходила крізь гео-ворота.", related_name='null_region_publish_configs', to='analysis.tag', verbose_name='Без регіону — лише з тегами'),
        ),
    ]
