# Generated by Django 5.2.17 on 2026-09-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0076_publish_null_region_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='require_tags',
            field=models.ManyToManyField(blank=True, help_text='Подія публікується лише якщо має ХОЧА Б ОДИН із цих тегів — на додачу до фільтра «Теги». Потрібно для порога важливості: виключення не ловить подію, у якої тега важливості НЕМА ЗОВСІМ (модель іноді його не ставить), і рутина проходила в канал.', related_name='required_publish_configs', to='analysis.tag', verbose_name="Обов'язкові теги (І)"),
        ),
    ]
