# Generated by Django 5.2.17 on 2026-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0077_publish_require_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishconfig',
            name='stop_patterns',
            field=models.TextField(blank=True, default='', help_text='Подія НЕ публікується, якщо будь-яка регулярка збігається з текстом поста або з резюме події. Для правил, які модель ігнорує попри промпт: у виборчому моніторі так відсіювали «Путін проголосував» — замовник ставив 👎, а скрін уперто давав важливість 3. Порожній рядок і рядок, що починається з #, пропускаються.', verbose_name='Стоп-фрази (регулярки, по одній на рядок)'),
        ),
    ]
