# Generated by Django 5.2.17 on 2026-09-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0078_publishconfig_stop_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishconfig',
            name='stop_patterns',
        ),
        migrations.AlterField(
            model_name='publishconfig',
            name='raw_mode',
            field=models.BooleanField(default=False, help_text='Публікувати ОРИГІНАЛЬНИЙ текст повідомлення/поста замість переказу від ШІ — нуль спотворень. Рерайту немає, але AI-промпт нижче працює: якщо він заповнений, ШІ вирішує ЧИ публікувати (фільтр), а в канал усе одно йде текст першоджерела. Порожній AI-промпт = LLM не викликається зовсім.', verbose_name='Без ШІ: оригінал + теги'),
        ),
    ]
