# Generated by Django 5.2.17 on 2026-09-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0079_remove_publishconfig_stop_patterns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishconfig',
            name='raw_header',
        ),
    ]
