# Generated by Django 5.2.17 on 2026-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0080_remove_publishconfig_raw_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='display_name',
            field=models.CharField(blank=True, db_default='', help_text='Людська назва секції у простому інтерфейсі (/app/), напр. «Інформпростір регіонів». Порожньо = показувати «Назва».', max_length=120, verbose_name='Назва для користувача'),
        ),
    ]
