# Generated by Django 5.2.17 on 2026-09-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0081_analysistask_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistask',
            options={'verbose_name': 'Дослідження', 'verbose_name_plural': 'Дослідження'},
        ),
    ]
