# Generated by Django 5.2.17 on 2026-09-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0082_analysistask_verbose_study'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Збір', 'verbose_name_plural': 'Збори'},
        ),
    ]
