# Generated by Django 5.2.17 on 2026-09-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0083_researchrun_verbose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал / джерело', 'verbose_name_plural': 'Довідник каналів і джерел'},
        ),
        migrations.AddField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('web', 'Сайт'), ('rss', 'RSS')], db_default='telegram', db_index=True, default='telegram', max_length=12, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='channel',
            name='url',
            field=models.CharField(blank=True, db_default='', db_index=True, help_text='Нормалізована адреса — ключ довідника (https://t.me/name, https://vk.com/club…, https://site/розділ). Заповнює код.', max_length=500, verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='source',
            name='channel',
            field=models.OneToOneField(blank=True, help_text='Довідник каналів і джерел (1:1): назва, регіон, підписники живуть там. Заповнює directory_backfill / код створення джерела.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='analysis.channel', verbose_name='Рядок довідника'),
        ),
    ]
