# Generated by Django 5.2.17 on 2026-09-28 09:06

from django.db import migrations, models


def set_source_from_history(apps, schema_editor):
    """Наявні monitor-задачі: розпізнати вибіркові, бо дефолт поля — telezip, і без
    цього кроку вже працююче вибіркове дослідження показувало б у картці
    неправдивий спосіб збору.

    Дві незалежні ознаки, бо MonitorSample могли й не зберегтись (ранні прогони):
      * є паспорти вибірки (MonitorSample);
      * пости є, а жодного TeleZip-чанка немає — суцільним збором такі пости
        зʼявитися не могли, CollectChunk створюється на кожен запит.
    """
    Task = apps.get_model("analysis", "AnalysisTask")
    Post = apps.get_model("analysis", "Post")
    Chunk = apps.get_model("analysis", "CollectChunk")
    Sample = apps.get_model("analysis", "MonitorSample")
    sampled = set(Sample.objects.values_list("task_id", flat=True).distinct())
    with_posts = set(Post.objects.values_list("task_id", flat=True).distinct())
    with_chunks = set(Chunk.objects.values_list("task_id", flat=True).distinct())
    ids = sampled | (with_posts - with_chunks)
    Task.objects.filter(pipeline="monitor", id__in=list(ids)).update(
        mon_collect_source="tg_sample")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0088_group_source_event_analyst'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='mon_collect_source',
            field=models.CharField(choices=[('telezip', 'TeleZip — суцільний потік за запитом (воркер mon_collect)'), ('tg_sample', 'Telegram-акаунти — випадкова вибірка (monitor_sample_collect)')], db_default='telezip', default='telezip', help_text='ЗВІДКИ беруться коментарі — далі обидва шляхи йдуть тими самими стадіями filter→prescreen→tag. telezip: суцільний потік, платний (~$0.10/чанк), читає «Пошуковий запит TeleZip» і «Розмір чанка», запускається через «Збори». tg_sample: випадкова вибірка id повідомлень Telegram-акаунтами (команда monitor_sample_collect, паспорт вибірки — «Вибірки (вікна)»); запит TeleZip і чанк у цьому режимі НЕ читаються, натомість кожному чату потрібен акаунт.', max_length=12, verbose_name='Спосіб збору коментарів'),
        ),
        migrations.RunPython(set_source_from_history, migrations.RunPython.noop),
    ]
