# Generated by Django 5.2.17 on 2026-09-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0089_monitor_collect_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSampleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Період з')),
                ('date_to', models.DateField(verbose_name='Період по (включно)')),
                ('mode', models.CharField(choices=[('collect', 'Збір (пише пости)'), ('probe', 'Розвідка чатів (--probe, постів не пише)'), ('dry_run', 'Кошторис (--dry-run, Telegram не читається)')], default='collect', max_length=8, verbose_name='Режим')),
                ('per_region', models.PositiveIntegerField(default=1500, help_text='Цільова вибірка на регіон. 1500 дають ±1 в.п. при частці ~4%.', verbose_name='Квота на регіон')),
                ('probe_ids', models.PositiveIntegerField(default=0, help_text='Лише для режиму probe: скільки випадкових id узяти в КОЖНОМУ чаті.', verbose_name='Розвідка: id на чат')),
                ('regions', models.CharField(blank=True, help_text='Порожньо = усі регіони задачі.', max_length=500, verbose_name='Лише ці регіони (кома)')),
                ('seed', models.PositiveIntegerField(default=0, help_text='0 = випадкове. Ненульове робить вибірку відтворюваною.', verbose_name='Зерно ГВЧ')),
                ('resume', models.BooleanField(default=False, help_text='Пропустити чати, для яких пости за цей період уже є.', verbose_name='Продовжити (--resume)')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('done', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Захоплено')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Спроб')),
                ('log', models.TextField(blank=True, verbose_name='Вивід команди')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Замовив')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_jobs', to='analysis.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вибірка — завдання на збір',
                'verbose_name_plural': 'Вибірки — завдання на збір',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='analysis_mo_status_3fcc9f_idx')],
            },
        ),
    ]
