# Generated by Django 5.2.17 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0090_monitorsamplejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsamplejob',
            name='mode',
            field=models.CharField(choices=[('collect', 'Збір (пише пости)'), ('probe', 'Розвідка чатів (--probe, постів не пише)'), ('dry_run', 'Кошторис (--dry-run, читає лише межі періоду, постів не пише)')], default='collect', max_length=8, verbose_name='Режим'),
        ),
    ]
