# Generated by Django 5.2.17 on 2026-10-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0091_alter_monitorsamplejob_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorsample',
            options={'ordering': ['-period_start', 'channel_id'], 'verbose_name': 'Паспорт вибірки', 'verbose_name_plural': 'Паспорти вибірки (чат × період збору)'},
        ),
        migrations.AddField(
            model_name='post',
            name='sample',
            field=models.ForeignKey(blank=True, help_text='Для збору вибіркою: з якого чату за який період узято цей коментар. Звідси береться вага коментаря для графіка частки. Порожньо = суцільний збір або зібране до запровадження ваг (такі коментарі важать 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.monitorsample', verbose_name='Паспорт вибірки'),
        ),
        migrations.AlterField(
            model_name='monitorsample',
            name='n_requested',
            field=models.PositiveIntegerField(default=0, help_text='Скільки номерів повідомлень ФАКТИЧНО запитали в Telegram. Якщо збір обірвався на обмеженні Telegram, тут менше, ніж планувалось, — інакше вага коментаря такого чату вийшла б заниженою.', verbose_name='Запитано номерів'),
        ),
        migrations.AlterField(
            model_name='monitorsample',
            name='n_user',
            field=models.PositiveIntegerField(default=0, help_text='Решта — автопересилки постів каналу в групу обговорень (анкери, під якими пишуть коментарі). У групі новинного каналу вони можуть давати 99% потоку, тому «повідомлень на добу» без цієї поправки міряє активність КАНАЛУ, а не людей.', verbose_name='З них повідомлень від людей'),
        ),
    ]
