# Generated by Django 5.2.17 on 2026-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0092_alter_monitorsample_options_post_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='mon_collect_source',
            field=models.CharField(choices=[('telezip', 'TeleZip — суцільний потік за запитом (воркер mon_collect)'), ('tg_sample', 'Telegram-акаунти — випадкова вибірка (monitor_sample_collect)'), ('vk_comments', 'VK — коментарі під постами спільнот (воркер mon_collect)')], db_default='telezip', default='telezip', help_text='ЗВІДКИ беруться коментарі — далі всі шляхи йдуть тими самими стадіями filter→prescreen→tag. telezip: суцільний потік, платний (~$0.10/чанк), читає «Пошуковий запит TeleZip» і «Розмір чанка», запускається через «Збори». tg_sample: випадкова вибірка id повідомлень Telegram-акаунтами (команда monitor_sample_collect, паспорт вибірки — «Вибірки (вікна)»); запит TeleZip і чанк у цьому режимі НЕ читаються, натомість кожному чату потрібен акаунт. vk_comments: коментарі під постами спільнот VK (у «Чатах» мають бути рядки довідника vk.com/…), збір безкоштовний і запускається через «Збори», як TeleZip-потік; запит TeleZip не читається.', max_length=12, verbose_name='Спосіб збору коментарів'),
        ),
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('telegram', 'Telegram-канал (акаунт)'), ('rss', 'RSS-стрічка'), ('web', 'Сайт (скрапінг)'), ('vk', 'VK-спільнота (API)')], db_index=True, max_length=12, verbose_name='Тип'),
        ),
    ]
