# Generated by Django 5.2.17 on 2026-09-19 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64, unique=True, verbose_name='client_id')),
                ('client_secret_hash', models.CharField(blank=True, help_text='Порожньо — публічний клієнт (PKCE без секрету).', max_length=64, verbose_name='Хеш client_secret')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Назва')),
                ('redirect_uris', models.JSONField(default=list, verbose_name='Redirect URI')),
                ('scope', models.CharField(blank=True, max_length=200, verbose_name='Запитані скоупи')),
                ('grant_types', models.JSONField(default=list, verbose_name='Grant types')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'MCP-клієнт (OAuth)',
                'verbose_name_plural': 'MCP-клієнти (OAuth)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш коду')),
                ('redirect_uri', models.CharField(max_length=500, verbose_name='Redirect URI')),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('code_challenge', models.CharField(blank=True, max_length=128, verbose_name='PKCE challenge')),
                ('scopes', models.JSONField(default=list, verbose_name='Скоупи')),
                ('resource', models.CharField(blank=True, max_length=500, verbose_name='Resource (RFC 8707)')),
                ('expires_at', models.DateTimeField(verbose_name='Дійсний до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='mcpauth.mcpclient', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Код авторизації MCP',
                'verbose_name_plural': 'Коди авторизації MCP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Читач — лише перегляд стану'), ('operator', 'Оператор — збори, чати, джерела, акаунти'), ('admin', 'Адмін — усе, включно з налаштуваннями й контейнерами')], default='reader', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_role', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Роль у MCP',
                'verbose_name_plural': 'Ролі у MCP',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='McpAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=10, verbose_name='Роль')),
                ('tool', models.CharField(db_index=True, max_length=64, verbose_name='Інструмент')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Параметри')),
                ('ok', models.BooleanField(default=True, verbose_name='Успіх')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='Помилка')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Тривалість, мс')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Коли')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_calls', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='mcpauth.mcpclient', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Виклик MCP (аудит)',
                'verbose_name_plural': 'Виклики MCP (аудит)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='mcpauth_mcp_user_id_8b4e93_idx')],
            },
        ),
        migrations.CreateModel(
            name='McpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хеш токена')),
                ('kind', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], default='access', max_length=8, verbose_name='Тип')),
                ('scopes', models.JSONField(default=list, verbose_name='Скоупи')),
                ('resource', models.CharField(blank=True, max_length=500, verbose_name='Resource')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний до')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Відкликано')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Востаннє вжито')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mcpauth.mcpclient', verbose_name='Клієнт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Токен MCP',
                'verbose_name_plural': 'Токени MCP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'revoked_at'], name='mcpauth_mcp_kind_8d49ea_idx')],
            },
        ),
    ]
