# Generated by Django 5.2.17 on 2026-09-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcpauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ запиту')),
                ('redirect_uri', models.CharField(max_length=500, verbose_name='Redirect URI')),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('code_challenge', models.CharField(blank=True, max_length=128, verbose_name='PKCE challenge')),
                ('scopes', models.JSONField(default=list, verbose_name='Запитані скоупи')),
                ('state', models.CharField(blank=True, max_length=300, verbose_name='state')),
                ('resource', models.CharField(blank=True, max_length=500, verbose_name='Resource')),
                ('expires_at', models.DateTimeField(verbose_name='Дійсний до')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests', to='mcpauth.mcpclient', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Запит авторизації MCP',
                'verbose_name_plural': 'Запити авторизації MCP',
                'ordering': ['-created_at'],
            },
        ),
    ]
