# Generated by Django 5.2.17 on 2026-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcpauth', '0002_mcpauthrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpclient',
            name='client_secret',
            field=models.CharField(blank=True, help_text='Порожньо — публічний клієнт (PKCE без секрету).', max_length=200, verbose_name='client_secret'),
        ),
        migrations.AlterField(
            model_name='mcpclient',
            name='client_secret_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хеш client_secret (легасі)'),
        ),
    ]
